// Padanan Inggris untuk seluruh label di modules.ts.
//
// KENAPA KAMUS BERKUNCI TEKS INDONESIA, BUKAN PASANGAN {id,en} SEBARIS.
//
// Pilihan yang lebih lazim adalah menulis `header: { id: "Nomor", en: "Number" }`
// langsung di modules.ts. Itu memang menghilangkan berkas ini, tetapi
// menggandakan panjang berkas registri dari 1.400 menjadi lebih dari 2.000
// baris — dan yang hilang bukan sekadar baris, melainkan kemampuan membaca
// SATU modul sebagai satu bentuk. Registri itu dibaca untuk menjawab
// "kolom apa saja yang tampil di daftar audit", dan jawaban itu jadi jauh
// lebih sulit dilihat ketika setiap kolom memakan dua baris.
//
// Yang membuat kamus berkunci-teks aman di sini, dan tidak selalu aman di
// tempat lain: labelnya adalah istilah domain QHSE, dan istilah domain
// diterjemahkan sama di mana pun ia muncul. "Nomor" adalah "Number" pada
// dokumen, audit, dan izin kerja sekaligus. Kekaburan yang biasanya
// merepotkan kamus semacam ini — satu kata sumber yang butuh dua terjemahan
// berbeda menurut konteks — tidak muncul pada daftar istilah teknis.
//
// SATU HAL YANG WAJIB: setiap label baru di modules.ts harus punya barisnya
// di sini. Itu tidak dijaga oleh harapan — `pnpm --filter @qhse/web check:i18n`
// memindai modules.ts dan gagal menyebutkan setiap label yang belum
// diterjemahkan. Tanpa langkah itu, modul ke-20 akan tampil setengah
// Indonesia di antarmuka Inggris dan tidak ada yang tahu sampai ada yang
// mengeluh.

export const KAMUS_MODUL: Record<string, string> = {
  // --- Kelompok sidebar ---
  "Dokumen & Kepatuhan": "Documents & Compliance",
  "Risiko & Operasi": "Risk & Operations",
  "Kejadian & Perbaikan": "Incidents & Corrective Action",
  "Inspeksi & Audit": "Inspection & Audit",
  "Mutu & Lingkungan": "Quality & Environment",
  "Kesehatan & Darurat": "Health & Emergency",
  "Kompetensi & Pelatihan": "Competency & Training",
  "Aset & Mitra Kerja": "Assets & Contractors",
  Pengaturan: "Settings",

  // --- Judul modul ---
  "Dokumen Terkendali": "Controlled Documents",
  "Register Peraturan": "Regulatory Register",
  "Penilaian HIRA": "HIRA Assessment",
  "Izin Kerja (PTW)": "Work Permit (PTW)",
  "Laporan Insiden": "Incident Reports",
  "Register CAPA": "CAPA Register",
  "Catatan Inspeksi": "Inspection Records",
  Audit: "Audit",
  "NCR Mutu": "Quality NCR",
  "Aspek & Dampak Lingkungan": "Environmental Aspects & Impacts",
  "Penugasan Kerja Terbatas": "Restricted Duty Assignment",
  "Rencana Tanggap Darurat": "Emergency Response Plan",
  "Aset & Peralatan": "Assets & Equipment",
  "Item Kalibrasi": "Calibration Items",
  Kontraktor: "Contractors",
  "Program Pelatihan": "Training Programme",
  "Realisasi Pelatihan": "Training Delivery",
  "Indikator Balanced Scorecard": "Balanced Scorecard Indicators",
  "Statistik HSE Bulanan": "Monthly HSE Statistics",

  // --- Nomor modul ---
  "Modul 03": "Module 03",
  "Modul 04": "Module 04",
  "Modul 05": "Module 05",
  "Modul 06": "Module 06",
  "Modul 07": "Module 07",
  "Modul 08": "Module 08",
  "Modul 09": "Module 09",
  "Modul 10": "Module 10",
  "Modul 11": "Module 11",
  "Modul 12": "Module 12",
  "Modul 13": "Module 13",
  "Modul 14": "Module 14",
  "Modul 15": "Module 15",
  "Modul 16": "Module 16",
  "Modul 17": "Module 17",
  "Modul 19": "Module 19",

  // --- Blok pencatatan ---
  Pencatatan: "Record keeping",
  "Dibuat oleh": "Created by",
  "Dibuat pada": "Created at",
  "Diubah terakhir oleh": "Last modified by",
  "Diubah pada": "Modified at",

  // --- Identitas ---
  "Identitas dokumen": "Document identity",
  "Identitas peraturan": "Regulation identity",
  "Identitas penilaian": "Assessment identity",
  "Identitas izin": "Permit identity",
  "Identitas insiden": "Incident identity",
  "Identitas CAPA": "CAPA identity",
  "Identitas inspeksi": "Inspection identity",
  "Identitas audit": "Audit identity",
  "Identitas ketidaksesuaian": "Nonconformity identity",
  "Identitas aspek": "Aspect identity",
  "Identitas rencana": "Plan identity",
  "Identitas aset": "Asset identity",
  "Identitas alat ukur": "Measuring instrument identity",
  "Identitas perusahaan": "Company identity",
  "Identitas program": "Programme identity",

  // --- Nomor dan penamaan ---
  Nomor: "Number",
  "Nomor dokumen": "Document number",
  "Nomor peraturan": "Regulation number",
  "Nomor HIRA": "HIRA number",
  "Nomor izin": "Permit number",
  "Nomor laporan": "Report number",
  "Nomor CAPA": "CAPA number",
  "Nomor catatan": "Record number",
  "Nomor audit": "Audit number",
  "Nomor NCR": "NCR number",
  "Nomor register": "Register number",
  "Nomor rencana": "Plan number",
  "Nomor program": "Programme number",
  "Nomor realisasi": "Delivery number",
  "Nomor seri": "Serial number",
  "Nomor sertifikat": "Certificate number",
  "No. sertifikat": "Certificate no.",
  "Nomor lot": "Lot number",
  "Nomor akta / NIB": "Deed / NIB number",
  "Nomor rujukan sumber": "Source reference number",
  "Nomor sasaran": "Objective number",
  "Kode sasaran": "Objective code",
  "Kode aset": "Asset code",
  "Kode produk": "Product code",
  Kode: "Code",
  Judul: "Title",
  "Judul program": "Programme title",
  "Judul sasaran": "Objective title",
  "Judul sesi": "Session title",
  Nama: "Name",
  "Nama aset": "Asset name",
  "Nama berkas": "File name",
  "Nama indikator": "Indicator name",
  "Nama perusahaan": "Company name",
  "Nama narahubung": "Contact person",

  // --- Klasifikasi umum ---
  Jenis: "Type",
  Tipe: "Type",
  "Tipe / model": "Type / model",
  Kategori: "Category",
  Klasifikasi: "Classification",
  "Klasifikasi awal": "Initial classification",
  Status: "Status",
  "Status siklus hidup": "Lifecycle status",
  "Status dan penempatan": "Status and deployment",
  Prioritas: "Priority",
  Peran: "Role",
  Urutan: "Sequence",
  Versi: "Version",
  Revisi: "Revision",
  Ukuran: "Size",
  Satuan: "Unit",
  Tingkat: "Level",
  Sumber: "Source",
  Tag: "Tag",
  Wajib: "Mandatory",
  Hasil: "Result",
  Skor: "Score",
  Target: "Target",
  Catatan: "Notes",
  Uraian: "Description",
  Ringkasan: "Summary",
  Kesimpulan: "Conclusion",
  Rekomendasi: "Recommendation",
  Frekuensi: "Frequency",
  Metode: "Method",
  Lokasi: "Location",
  Tempat: "Venue",
  Departemen: "Department",
  Perusahaan: "Company",
  Jabatan: "Position",
  Pekerja: "Worker",
  Pekerjaan: "Work",
  Kondisi: "Condition",
  Keputusan: "Decision",
  Masalah: "Problem",
  Alasan: "Reason",
  Parameter: "Parameter",
  Pasal: "Article",
  Skenario: "Scenario",
  Langkah: "Step",
  Tindakan: "Action",
  Temuan: "Findings",
  Investigasi: "Investigation",
  Risiko: "Risk",
  Bahaya: "Hazard",
  Kemungkinan: "Likelihood",
  Keparahan: "Severity",
  Signifikansi: "Significance",
  Sertifikasi: "Certification",
  Pelaksanaan: "Delivery",
  Penyelenggaraan: "Organisation",
  Penugasan: "Assignment",
  Pengukuran: "Measurement",
  Peninjauan: "Review",
  Legalitas: "Legal standing",
  Rencana: "Plan",
  Realisasi: "Actual",
  Program: "Programme",
  Pelatihan: "Training",
  Sesi: "Session",
  Hadir: "Attended",
  Kehadiran: "Attendance",
  Keefektifan: "Effectiveness",
  Instruktur: "Trainer",
  Penyelenggara: "Provider",
  Penyedia: "Provider",
  Pemasok: "Supplier",
  Penerbit: "Issuer",
  Pemeriksa: "Inspector",
  Pemohon: "Requester",
  PIC: "PIC",
  Anggaran: "Budget",
  Biaya: "Cost",
  "Biaya realisasi": "Actual cost",
  Jam: "Hours",
  Bulan: "Month",
  Mulai: "Start",
  Selesai: "End",
  Terbit: "Issued",
  Terdaftar: "Registered",
  "Terdaftar sejak": "Registered since",
  Terdeteksi: "Detected",
  Berlaku: "Effective",
  "Berlaku sampai": "Valid until",
  Tanggal: "Date",
  Kota: "City",
  Provinsi: "Province",
  Alamat: "Address",
  Telepon: "Phone",
  Surel: "Email",
  NPWP: "Tax ID (NPWP)",
  Pabrikan: "Manufacturer",
  Area: "Area",
  "Area proses": "Process area",
  Aktivitas: "Activity",
  "Aktivitas / area": "Activity / area",
  "Aktivitas yang dinilai": "Assessed activity",
  Kejadian: "Event",
  Insiden: "Incidents",
  // Tetap "Balanced Scorecard" — istilah Kaplan & Norton dipakai apa adanya
  // di kedua bahasa, termasuk dalam dokumen berbahasa Indonesia.
  "Balanced Scorecard": "Balanced Scorecard",
  Kronologi: "Chronology",
  Disposisi: "Disposition",
  Peringkat: "Rating",
  Capaian: "Achieved",
  Perspektif: "Perspective",
  Sasaran: "Objective",
  Induksi: "Induction",
  "Toolbox talk": "Toolbox talk",
  "Rapat HSE": "HSE meeting",
  "Kunjungan manajemen": "Management walkthrough",
  "Observasi keselamatan": "Safety observation",
  "Tindakan tidak aman": "Unsafe acts",
  "Kondisi tidak aman": "Unsafe conditions",
  "Leading indicator": "Leading indicators",
  "Jam kerja": "Man-hours",
  "Man-hours": "Man-hours",
  "Jam pelatihan": "Training hours",
  "Tenaga kerja": "Manpower",
  "Jumlah tenaga kerja": "Manpower count",
  "Jumlah pekerja": "Worker count",
  "Safety critical": "Safety critical",
  "Butuh CAPA": "CAPA required",
  "Diatur regulasi": "Regulated",
  "Matriks risiko": "Risk matrix",

  // --- Judul bagian detail ---
  "Isi dokumen": "Document content",
  "Ringkasan isi": "Content summary",
  "Ringkasan perubahan": "Change summary",
  "Ringkasan temuan": "Findings summary",
  "Ringkasan dan relevansi": "Summary and relevance",
  "Masa berlaku dan peninjauan": "Validity and review",
  "Mulai berlaku": "Effective from",
  "Tinjauan berikutnya": "Next review",
  "Tinjauan terakhir": "Last review",
  "Siklus tinjauan (bulan)": "Review cycle (months)",
  "Masa retensi (tahun)": "Retention period (years)",
  "Masa berlaku": "Validity",
  "Jatuh tempo": "Due",
  "Jatuh tempo berikutnya": "Next due",
  "Jatuh tempo tinjauan": "Review due",
  "Acuan klausul ISO": "ISO clause reference",
  "Pemilik dokumen": "Document owner",
  "Riwayat versi": "Version history",
  "Instansi penerbit": "Issuing authority",
  "Jenis izin usaha": "Business licence type",
  "Aspek regulasi": "Regulatory aspects",
  "Perhatian pemangku kepentingan": "Stakeholder concern",
  "Kewajiban kepatuhan": "Compliance obligations",
  Kewajiban: "Obligation",
  "Salinan peraturan": "Regulation copy",
  "Tanggal terbit": "Issue date",
  "Tanggal dan peninjauan": "Dates and review",

  // --- HIRA ---
  "Bahaya dan pengendalian": "Hazards and controls",
  "Pengendalian yang ada": "Existing controls",
  "Pengendalian tambahan": "Additional controls",
  "Tingkat risiko": "Risk level",
  "Tingkat awal": "Initial level",
  "Tingkat sisa": "Residual level",
  "Skor awal": "Initial score",
  "Skor sisa": "Residual score",
  "Peringkat risiko": "Risk rating",
  "Uraian aktivitas": "Activity description",
  "Dinilai oleh": "Assessed by",
  "Tanggal penilaian": "Assessment date",
  "Jenis penilaian": "Assessment type",

  // --- Izin kerja ---
  "Jenis izin": "Permit type",
  "Jenis pekerjaan": "Work type",
  "Uraian pekerjaan": "Work description",
  "Lokasi dan waktu": "Location and time",
  "Rincian lokasi": "Location detail",
  "Hasil uji gas": "Gas test results",
  "Jenis gas": "Gas type",
  "Hasil ukur": "Measured value",
  "Waktu uji": "Test time",
  "Diuji oleh": "Tested by",
  "Lokasi kerja": "Site",

  // --- Insiden ---
  "Tempat, waktu, dan dampak": "Place, time, and impact",
  "Waktu kejadian": "Event time",
  "Dilaporkan oleh": "Reported by",
  "Hari hilang": "Days lost",
  "Hari kerja hilang": "Lost workdays",
  "Estimasi kerugian": "Estimated loss",
  "Tindakan segera": "Immediate action",
  "Tindakan penahanan segera": "Immediate containment",
  "Uraian dan penanganan": "Description and response",
  "Ketua investigasi": "Lead investigator",
  "Akar masalah": "Root cause",
  "Analisis akar masalah": "Root cause analysis",
  "Jenis sebab": "Cause type",
  "Faktor penyumbang": "Contributing factor",
  "Tindak lanjut — CAPA terkait": "Follow-up — related CAPA",
  "Tanggal analisis": "Analysis date",
  "Dianalisis oleh": "Analysed by",
  "Pernyataan masalah": "Problem statement",
  "Rencana tindakan": "Action plan",
  "Penanggung jawab": "Person in charge",
  "Penanggung jawab dan target": "Owner and target",
  "Target penutupan": "Target closure",
  "Target selesai": "Target completion",
  "Realisasi penutupan": "Actual closure",
  "Tanggal ditutup": "Closed on",
  "Ditutup oleh": "Closed by",
  "Diprakarsai oleh": "Initiated by",
  "Tanggal prakarsa": "Initiated on",
  "Ditemukan oleh": "Found by",
  "Diidentifikasi oleh": "Identified by",
  "Ditautkan oleh": "Linked by",
  "Ditautkan pada": "Linked on",
  "Dikerjakan oleh": "Performed by",
  "Ditetapkan oleh": "Defined by",
  "Ditinjau oleh": "Reviewed by",
  "Disetujui oleh": "Approved by",
  "Disetujui pada": "Approved on",
  "Disahkan oleh": "Authorised by",
  "Tanggal pengesahan": "Authorisation date",
  "Disiapkan oleh": "Prepared by",
  "Dievaluasi oleh": "Evaluated by",
  "Terdeteksi oleh": "Detected by",
  "Tanggal terdeteksi": "Detected on",
  "Tahap deteksi": "Detection stage",
  "Dikonfirmasi atasan": "Confirmed by supervisor",
  "Diunggah oleh": "Uploaded by",
  "Waktu unggah": "Uploaded at",

  // --- Inspeksi & audit ---
  "Checklist / standar": "Checklist / standard",
  "Checklist yang dipakai": "Checklist used",
  "Pelaksanaan dan hasil": "Execution and results",
  "Hasil keseluruhan": "Overall result",
  "Hasil observasi": "Observation result",
  "Hasil inspeksi ulang": "Re-inspection result",
  "Catatan pemeriksa": "Inspector notes",
  "Temuan inspeksi": "Inspection findings",
  "Temuan audit": "Audit findings",
  "Temuan dan pekerjaan": "Findings and work",
  "Jenis audit": "Audit type",
  "Ketua auditor": "Lead auditor",
  "Tim audit": "Audit team",
  "Lokasi yang diaudit": "Audited location",
  "Kesimpulan audit": "Audit conclusion",
  "Jadwal dan pelaksanaan": "Schedule and execution",
  "Rapat pembukaan": "Opening meeting",
  "Rapat penutupan": "Closing meeting",
  "Notulen rapat pembukaan": "Opening meeting minutes",
  "Notulen rapat penutupan": "Closing meeting minutes",
  "Notulen dan kesimpulan": "Minutes and conclusion",
  "Tingkat keparahan": "Severity level",

  // --- NCR & mutu ---
  "Uraian ketidaksesuaian": "Nonconformity description",
  "Objek yang tidak sesuai": "Nonconforming item",
  "Produk / material": "Product / material",
  "Jumlah tidak sesuai": "Nonconforming quantity",
  "Kategori cacat": "Defect category",
  "Disposisi dan penutupan": "Disposition and closure",
  "Alasan disposisi": "Disposition reason",
  "Nilai awal": "Baseline value",
  "Capaian berjalan": "Current value",
  "Bobot %": "Weight %",
  "Bobot dalam perspektif (%)": "Weight within perspective (%)",
  "Awal periode": "Period start",
  "Akhir periode": "Period end",
  "Frekuensi pengukuran": "Measurement frequency",

  // --- Lingkungan ---
  "Aspek lingkungan": "Environmental aspect",
  "Aspek dan dampaknya": "Aspect and its impact",
  "Dampak lingkungan": "Environmental impact",
  "Jenis dampak": "Impact type",
  "Kondisi operasi": "Operating condition",
  "Penilaian signifikansi": "Significance assessment",
  "Skor signifikansi": "Significance score",
  "Ambang signifikan": "Significance threshold",

  // --- Kesehatan & darurat ---
  "Jenis pembatasan": "Restriction type",
  "Tugas alternatif": "Alternative duty",
  "Uraian tugas": "Duty description",
  "Atasan langsung": "Direct supervisor",
  "Jenis darurat": "Emergency type",
  "Jenis keadaan darurat": "Emergency type",
  "Uraian skenario": "Scenario description",
  "Langkah tanggap darurat": "Emergency response steps",
  "Target (menit)": "Target (minutes)",
  "Pengesahan dan peninjauan": "Authorisation and review",

  // --- Aset & kalibrasi ---
  "Tag peralatan": "Equipment tag",
  "Tanggal pembelian": "Purchase date",
  "Tanggal commissioning": "Commissioning date",
  "Kondisi akhir": "Current condition",
  "Kondisi saat diterima": "Condition on receipt",
  "Riwayat pemeliharaan": "Maintenance history",
  "Alat ukur": "Measuring instrument",
  "Parameter ukur": "Measured parameter",
  "Rentang dan interval": "Range and interval",
  "Batas bawah": "Lower limit",
  "Batas atas": "Upper limit",
  "Interval (bulan)": "Interval (months)",
  "Interval kalibrasi (bulan)": "Calibration interval (months)",
  "Tanggal kalibrasi": "Calibration date",
  "Sertifikat kalibrasi": "Calibration certificates",
  "Rujukan metode": "Method reference",
  Ketidakpastian: "Uncertainty",
  "Pengukuran kritis": "Critical measurement",

  // --- Kontraktor ---
  "Alamat dan narahubung": "Address and contact",
  "Evaluasi kinerja": "Performance evaluation",
  "Periode mulai": "Period start",
  "Periode selesai": "Period end",
  "Skor HSE": "HSE score",
  "Aset terkait": "Related asset",

  // --- Pelatihan ---
  "Jenis pelatihan": "Training type",
  "Tujuan pelatihan": "Training objective",
  "Sasaran dan dasar": "Target and basis",
  "Sasaran peserta": "Target audience",
  "Diwajibkan peraturan": "Required by regulation",
  "Dasar peraturan": "Regulatory basis",
  "Jumlah peserta direncanakan": "Planned participants",
  "Jam per peserta": "Hours per participant",
  "Jumlah sesi": "Number of sessions",
  "Rencana mulai": "Planned start",
  "Rencana selesai": "Planned end",
  "Rencana peserta": "Planned participants",
  "Menghasilkan sertifikat": "Produces certificate",
  "Masa berlaku sertifikat (bulan)": "Certificate validity (months)",
  "Tahun anggaran": "Fiscal year",
  "Realisasi pelatihan": "Training delivery",
  "Program yang dilaksanakan": "Programme delivered",
  "Tanggal pelaksanaan": "Delivery date",
  "Tanggal selesai": "End date",
  "Durasi (jam)": "Duration (hours)",
  "Kehadiran dan biaya": "Attendance and cost",
  "Peserta direncanakan": "Planned participants",
  "Peserta hadir": "Participants attended",
  "Peserta lulus": "Participants passed",
  "Evaluasi keefektifan": "Effectiveness evaluation",
  "Rata-rata nilai pra-uji": "Average pre-test score",
  "Rata-rata nilai pasca-uji": "Average post-test score",
  "Nilai pasca-uji": "Post-test score",
  "Penilaian keefektifan": "Effectiveness rating",
  "Cara evaluasi": "Evaluation method",
  "Catatan evaluasi": "Evaluation notes",
  "Tanggal evaluasi": "Evaluation date",
  "Sertifikat diterbitkan": "Certificate issued",
  "Daftar peserta": "Participant list",

  // --- Statistik & scorecard ---
  "Pembagi indikator kekerapan": "Frequency-rate denominator",
  "Induksi keselamatan": "Safety induction",
  "Tanggal rencana": "Planned date",
  "Tanggal realisasi": "Actual date",
  "Realisasi mulai": "Actual start",
  "Realisasi selesai": "Actual end",

  // --- Pesan kosong tabel anak ---
  "Dokumen ini belum punya versi yang tercatat.": "This document has no recorded versions yet.",
  "Belum ada kewajiban yang diturunkan dari peraturan ini.":
    "No obligations have been derived from this regulation yet.",
  "Belum ada salinan peraturan yang diunggah.": "No copy of the regulation has been uploaded yet.",
  "Belum ada baris bahaya pada penilaian ini.": "This assessment has no hazard lines yet.",
  "Jenis izin ini tidak mensyaratkan uji gas.": "This permit type does not require gas testing.",
  "Insiden ini belum melewati investigasi formal.": "This incident has not gone through a formal investigation.",
  "Akar masalah belum ditetapkan — investigasinya belum selesai.":
    "Root causes have not been established — the investigation is not complete.",
  "Belum ada CAPA yang ditautkan ke insiden ini.": "No CAPA has been linked to this incident yet.",
  "CAPA ini masih berstatus draf; analisis akar masalah belum dikerjakan.":
    "This CAPA is still a draft; root cause analysis has not been carried out.",
  "Belum ada rencana tindakan yang ditetapkan.": "No action plan has been defined yet.",
  "Tidak ada temuan pada inspeksi ini.": "This inspection recorded no findings.",
  "Audit ini belum dilaksanakan, jadi belum ada temuan.": "This audit has not been carried out, so there are no findings yet.",
  "Tim audit belum ditetapkan.": "The audit team has not been appointed yet.",
  "Langkah tanggap darurat belum disusun.": "Emergency response steps have not been drawn up yet.",
  "Belum ada rekaman pemeliharaan untuk aset ini.": "No maintenance records for this asset yet.",
  "Belum ada sertifikat kalibrasi untuk alat ini.": "No calibration certificates for this instrument yet.",
  "Kontraktor ini belum pernah dievaluasi — belum ada penugasan yang selesai.":
    "This contractor has not been evaluated — no assignment has been completed.",
  "Program ini belum pernah dilaksanakan — belum ada sesi yang tercatat.":
    "This programme has never been delivered — no session recorded.",
  "Sesi ini tidak mendaftar peserta per nama — kehadirannya dicatat sebagai jumlah.":
    "This session does not list participants by name — attendance is recorded as a count.",
};
